"""init

Revision ID: d324e2482509
Revises: 
Create Date: 2026-05-02 19:11:35.683645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd324e2482509'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gruppi_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('permessi', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('tipi_eventi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipi_transazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('descrizione', sa.String(length=128), nullable=False),
    sa.Column('calcolata', sa.JSON(), nullable=False),
    sa.Column('formula', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tipi_variabili',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('formula', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('cognome', sa.String(length=128), nullable=False),
    sa.Column('mail', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('gruppo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gruppo'], ['gruppi_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('eventi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=128), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('responsabile', sa.Integer(), nullable=False),
    sa.Column('stato', sa.String(length=128), nullable=False),
    sa.Column('data_inizio', sa.Date(), nullable=False),
    sa.Column('data_fine', sa.Date(), nullable=True),
    sa.Column('localita', sa.String(length=128), nullable=False),
    sa.Column('iscritti', sa.Integer(), nullable=False),
    sa.Column('partecipanti', sa.Integer(), nullable=False),
    sa.Column('quota_acconto', sa.Integer(), nullable=False),
    sa.Column('quota_saldo', sa.Integer(), nullable=False),
    sa.Column('staff', sa.Integer(), nullable=False),
    sa.Column('iban', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['responsabile'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tipo'], ['tipi_eventi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transazioni',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_transazione', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Integer(), nullable=False),
    sa.Column('descrizione', sa.String(length=128), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('importo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento'], ['eventi.id'], ),
    sa.ForeignKeyConstraint(['tipo_transazione'], ['tipi_transazioni.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transazioni')
    op.drop_table('eventi')
    op.drop_table('users')
    op.drop_table('tipi_variabili')
    op.drop_table('tipi_transazioni')
    op.drop_table('tipi_eventi')
    op.drop_table('system_option')
    op.drop_table('gruppi_user')
    # ### end Alembic commands ###
