name: BE Tests and Build Docker Image

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: "secret"
      DB_TYPE: "sqlite"
      DB_USER: ""
      DB_PASSWORD: ""
      DB_HOST: ""
      DB_PORT: ""
      DB_NAME: ""
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: pytest --cov=app
    
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag ghcr.io/calminaro/gestionale_eventi_agesci:dev

    - name: Push Docker image
      run: |
        docker push ghcr.io/calminaro/gestionale_eventi_agesci:dev
