name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: pytest --cov=app
  
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag ghcr.io/calminaro/gestionale_eventi_agesci:${{ github.sha }} \
          --tag ghcr.io/calminaro/gestionale_eventi_agesci:latest

    - name: Push Docker image
      run: |
        docker push ghcr.io/calminaro/gestionale_eventi_agesci:${{ github.sha }}
        docker push ghcr.io/calminaro/gestionale_eventi_agesci:latest
